### ISSUE TITLE
Organização das palestras

### ISSUE THREAD

**Issue by caloni** [ccppbrasil/encontro11#1]
Vocês acham que é uma boa dividir as palestras por encontro? Quer dizer, criar um repositório apenas para cada encontro? Ou manter todas em um só repo?

**Comment by walac** [comment]
Acho que separar por encontro fica melhor.

**Comment by oblitum** [comment]
Tb acho melhor, ao estilo gringo: https://github.com/boostcon

**Comment by caloni** [comment]
OK.

[]s

2015-03-29 11:22 GMT-03:00 Francisco Lopes notifications@github.com:

> Tb acho melhor, ao estilo gringo: https://github.com/boostcon
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ccppbrasil/encontro11/issues/1#issuecomment-87420902.

## 

Wanderley Caloni
http://www.caloni.com.br
